version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: france_chomage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # France Chômage Bot
  app:
    build: ../../.
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database configuration
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/france_chomage
      DOCKER_ENV: "true"
      
      # Telegram configuration (from .env file)
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_GROUP_ID: ${TELEGRAM_GROUP_ID}
      TELEGRAM_COMMUNICATION_TOPIC_ID: ${TELEGRAM_COMMUNICATION_TOPIC_ID:-3}
      TELEGRAM_DESIGN_TOPIC_ID: ${TELEGRAM_DESIGN_TOPIC_ID:-40}
      TELEGRAM_RESTAURATION_TOPIC_ID: ${TELEGRAM_RESTAURATION_TOPIC_ID:-326}
      
      # Scraping configuration
      RESULTS_WANTED: ${RESULTS_WANTED:-20}
      LOCATION: ${LOCATION:-Paris}
      SKIP_INIT_JOB: ${SKIP_INIT_JOB:-0}
      
      # Anti-detection settings
      FORCE_DOCKER_MODE: "1"  # Force LinkedIn-only mode in Docker
      MAX_RETRIES: "3"
      INDEED_MAX_RESULTS: "5"  # Conservative limit for Indeed
    volumes:
      - ./logs:/app/logs
      - job_data:/app/data  # For backup files
    ports:
      - "8080:8080"  # For potential web interface
    healthcheck:
      test: ["CMD", "python", "-c", "from france_chomage.config import settings; print('App healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Adminer for database management
  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: "hydra"
    depends_on:
      - db
    profiles:
      - admin  # Only start with: docker-compose --profile admin up

volumes:
  postgres_data:
    driver: local
  job_data:
    driver: local

networks:
  default:
    name: france-chomage-network
